# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5acd1c34bf69b0c4ac53c75ac981a6e44cd4f1ff54039424c0d22699a43f0971818fd9592debf6187d737be70a32e1920ad130a1a073eeaf8e3c6ab214fd9590

test:
  secret_key_base: 8c30bcb728556428bcb1e49e32eca2b0472a3fc2721fa55f5e7b114e2197079ac3e40c9f1d467ec7449d0385199d78442f0dadfbe073161e5fe679db11ab929c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
